@startuml Architecture
package "Frontend (React)" {
    component [Admin Page] as Admin
    component [Events Listing Page] as Listing
    component [Event Details Page] as Details
}

package "Backend (Node.js)" {
    component [API Gateway] as API
    component [Authentication Service] as Auth
    component [Event Management Service] as EventMgmt
    component [User Managment Service] as UserMgmt
}

database "EventDatabase (MongoDB)" {
    component [Events] as EventsDB
}

database "UserDatabase (MongoDB)" {
    component [Users] as UsersDB
}

Auth --> API : Validates user and forwards to API
Admin --> Auth : Create/Update events
Listing --> Auth : Fetch all events
Details --> Auth : Fetch event details
API --> EventMgmt : Delegate event operations
API --> UserMgmt: CRUD user
EventMgmt --> EventsDB : Manage event data operations
UserMgmt --> UsersDB: Manage user data operation
@enduml