@startuml Interaction Flow
actor User

User -> EventCard : clicks
EventCard -> EventDetailsPage : navigate
EventDetailsPage -> EventDetailsView : displays detailed information
User -> BookingForm : submits application

@enduml
